services:
  php:
    build: .
    ports:
      - "8080:9000"
    depends_on:
      database:
        condition: service_healthy
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgresql://app:!ChangeMe!@database:5432/gem_vault?serverVersion=16&charset=utf8"
    volumes:
      - .:/app
      - uploads:/app/public/images/gemstones

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-gem_vault}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  database_data:
  uploads:
